# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile, black, --filter-files]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/akaihola/darker
  rev: 1.4.1
  hooks:
  - id: darker
    args: [--line-length, '139']
- repo: https://github.com/PyCQA/pylint/
  rev: v2.12.2
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args: [-rn, -sn, --rcfile=tests/.pylintrc]
    # "-rn", # Only display messages
    # "-sn", # Don't display the score
    # based on
    # https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html
